const locationArray = [
  'None',
  'Akaa',
  'Alajärvi',
  'Alavus',
  'Espoo',
  'Forssa',
  'Haapajärvi',
  'Haapavesi',
  'Hamina',
  'Hanko',
  'Harjavalta',
  'Heinola',
  'Helsinki',
  'Huittinen',
  'Hyvinkää',
  'Hämeenlinna',
  'Iisalmi',
  'Ikaalinen',
  'Imatra',
  'Pietarsaari',
  'Joensuu',
  'Jyväskylä',
  'Jämsä',
  'Järvenpää',
  'Kaarina',
  'Kajaani',
  'Kalajoki',
  'Kangasala',
  'Kankaanpää',
  'Kannus',
  'Karkkila',
  'Kaskinen',
  'Kauhajoki',
  'Kauhava',
  'Kauniainen',
  'Kemi',
  'Kemijärvi',
  'Kerava',
  'Keuruu',
  'Kitee',
  'Kiuruvesi',
  'Kokemäki',
  'Kokkola',
  'Kotka',
  'Kouvola',
  'Kristiinankaupunki',
  'Kuhmo',
  'Kuopio',
  'Kurikka',
  'Kuusamo',
  'Lahti',
  'Laitila',
  'Lappeenranta',
  'Lapua',
  'Lieksa',
  'Lohja',
  'Loimaa',
  'Loviisa',
  'Maarianhamina',
  'Mikkeli',
  'Mänttä-Vilppula',
  'Naantali',
  'Nivala',
  'Nokia',
  'Nurmes',
  'Uusikaarlepyy',
  'Närpiö',
  'Orimattila',
  'Orivesi',
  'Oulainen',
  'Oulu',
  'Outokumpu',
  'Paimio',
  'Parainen',
  'Parkano',
  'Pieksämäki',
  'Pori',
  'Porvoo',
  'Pudasjärvi',
  'Pyhäjärvi',
  'Raisio',
  'Raasepori',
  'Rauma',
  'Riihimäki',
  'Rovaniemi',
  'Saarijärvi',
  'Salo',
  'Sastamala',
  'Savonlinna',
  'Seinäjoki',
  'Somero',
  'Suonenjoki',
  'Tampere',
  'Tornio',
  'Turku',
  'Ulvila',
  'Uusikaupunki',
  'Vaasa',
  'Valkeakoski',
  'Vantaa',
  'Varkaus',
  'Viitasaari',
  'Virrat',
  'Ylivieska',
  'Ylöjärvi',
  'Ähtäri',
  'Äänekoski',
];
const countryArray = [
  'None',
  'Afghanistan',
  'Albania',
  'Algeria',
  'America',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory ',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands ',
  'Central African Republic ',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos Islands ',
  'Colombia',
  'Comoros ',
  'Congo',
  'Congo ',
  'Cook Islands ',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic ',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands  [Malvinas]',
  'Faroe Islands ',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories ',
  'Gabon',
  'Gambia ',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See ',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'South Korea',
  'North Korea',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic ",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands ',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands ',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger ',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands ',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines ',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of North Macedonia',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and  South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands',
];
const religionArray = [
  'None',
  'Christianity',
  'Islam',
  'Nonreligious',
  'Hinduism',
  'Buddhism',
  'Prefer not to say',
];
const educationArray = [
  'None',
  'Primary Education',
  'Secondary Education',
  'Vocational Education',
  'Undergraduate',
  'Postgraduate',
  'Prefer not to say',
];
const dataSource = [
  'Yoga',
  'Pets',
  'DIY',
  'Films',
  'Shopping',
  'Food',
  'Workout',
  'Travel',
  'Coffee',
  'Reading',
  'Music',
  'Outdoor',
  'Fashion',
  'Anime',
  'Game',
  'Photography',
  'Camping',
  'Sports',
  'Indoor',
  'Cook & Bake',
  'Astronomy',
  'Art',
  'Tech',
  'Collecting',
  'Gardening',
  'Puzzles',
  'Code',
  'Board games',
  'Writing',
  'Meditation',
  'Skiing',
  'Volunteer',
  'LEGO',
  'Drinking',
];

export {locationArray, countryArray, religionArray, educationArray, dataSource};
